name: "pooch-cache"
description: "Caches pooches cache"
inputs:
  name:
    description: "The name of the cache, as passed to pooch.os_cache"
    required: true
    default: "pooch-cache"
  dois:
    description: "DOIs from which to download. Pass as new line separated string."
  file-urls:
    description: "File URLs to download, requires known-hashes of same length. Pass as new line separated string."
  known-hashes:
    description: "Known hashes for file-urls download. Pass as new line separated string."
  base-urls:
    description: "Base URLs for download, requires registry-files of same length. Pass as new line separated string."
  registry-files:
    description: "Registry files which download. Pass as new line separated string."
  filename-whitelist:
    description: "A whitelist of filenames used when downloading files from registries (useful for e.g. partial downloads from a DOI)"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5

    - shell: bash
      run: python -m pip install pooch

    - shell: python
      env:
        XDG_CACHE_HOME: ~/.cache
      run: |
        import os
        import pooch

        # Get the cache location
        cache = pooch.os_cache("${{ inputs.name }}")

        # Parse the inputs into Python data structures

        def parse_array(s):
            return [item.strip() for item in s.split("\n") if item.strip()]

        dois = parse_array("""${{ inputs.dois }}""")
        file_urls = parse_array("""${{ inputs.file-urls }}""")
        known_hashes = parse_array("""${{ inputs.known-hashes }}""")
        base_urls = parse_array("""${{ inputs.base-urls }}""")
        registry_files = parse_array("""${{ inputs.registry-files }}""")
        whitelist = parse_array("""${{ inputs.filename-whitelist }}""")

        if len(base_urls) != len(registry_files):
            raise ValueError("Number of base URLs must match number of registry files")
        if len(file_urls) != len(known_hashes):
            raise ValueError("Number of file URLs must match number of known hashes")

        # Download all DOI content
        for doi in dois:
            p = pooch.Pooch(base_url=f"doi:{doi}", path=cache)
            p.load_registry_from_doi()

            for fn in p.registry:
                if whitelist and fn not in whitelist:
                    continue
                p.fetch(fn)

        # Download all registry content
        for base, reg in zip(base_urls, registry_files):
            p = pooch.Pooch(base_url=base_url, path=cache)
            p.load_registry(reg)

            for fn in p.registry:
                if whitelist and fn not in whitelist:
                    continue
                p.fetch(fn)

        # Download all files
        for url, hash in zip(file_urls, known_hashes):
            pooch.retrieve(url=url, known_hash=hash, path=cache)
  
    - name: Cache pooch cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/${{ inputs.name }}
        key: pooch-cache-${{ inputs.name }}
        enableCrossOsArchive: true
